[package]
name = "openal-rs"
description = "Rust bindings for OpenAL 1.1"
version = "0.4.0"
authors = ["bjz", "samyatchmenoff", "jpernst"]
license = "Apache-2.0"
repository = "https://github.com/jpernst/openal-rs.git"
documentation = "http://jpernst.github.io/openal-rs"
keywords = ["openal", "sound", "audio"]
build = "build.rs"

[build-dependencies]
pkg-config = "0.3.8"

[dependencies]
lazy_static = "0.2.1"

