[package]
name = "alto"
description = "[WIP] Idiomatic interface for OpenAL 1.1 and extensions (including EFX)"
version = "0.1.1"
authors = ["jpernst"]
license = "MIT/Apache-2.0"
repository = "https://github.com/jpernst/alto.git"
documentation = "https://docs.rs/alto"
keywords = ["openal", "al", "sound", "audio"]

[dependencies]
rental = "0.3.0"
lazy_static = "0.2.1"
al-sys = "0.3.0"

