[package]
name = "al-sys"
description = "Rust bindings for OpenAL 1.1"
version = "0.3.0"
authors = ["jpernst"]
license = "MIT/Apache-2.0"
repository = "https://github.com/jpernst/alto.git"
documentation = "https://docs.rs/al-sys"
keywords = ["openal", "al", "sound", "audio"]

[build-dependencies]
pkg-config = "0.3.8"

[dependencies]
libloading = "0.3.1"
rental = "0.3.0"

