[package]
name = "al-sys"
description = "Rust bindings for OpenAL 1.1"
version = "0.1.1"
authors = ["jpernst"]
license = "MIT/Apache-2.0"
repository = "https://github.com/jpernst/alto.git"
keywords = ["openal", "al", "sound", "audio"]

[build-dependencies]
pkg-config = "0.3.8"

[dependencies]
libloading = "0.3.1"
owning_ref = { git = "https://github.com/Kimundi/owning-ref-rs" }

